"""
Django settings for kfc_api project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys
import json
import tempfile
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
_IS_FROZEN = getattr(sys, 'frozen', False)
_RUNTIME_PATH = sys.executable if _IS_FROZEN else __file__
BASE_DIR = Path(os.path.dirname(os.path.abspath(_RUNTIME_PATH)))

# When running as source code, settings.py lives in kfc_api/kfc_api, so step up once.
if not _IS_FROZEN:
    BASE_DIR = BASE_DIR.parent

BASE_DIR = BASE_DIR.resolve()

# Load environment variables from the project .env file.
load_dotenv(BASE_DIR / '.env')


def _resolve_runtime_path(raw_path: str | None) -> str | None:
    """Resolve absolute paths for local and deployed environments."""
    if not raw_path:
        return None

    candidate = Path(os.path.expandvars(raw_path.strip())).expanduser()
    if not candidate.is_absolute():
        candidate = BASE_DIR / candidate
    return str(candidate.resolve())


google_service_account_json = os.getenv('GOOGLE_SERVICE_ACCOUNT_JSON')
if not google_service_account_json:
    raise EnvironmentError('GOOGLE_SERVICE_ACCOUNT_JSON environment variable must be set for Google authentication.')
json.loads(google_service_account_json)  # Validate JSON


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-lx236l^sw$gkx5o7ic&n0!t59@xrzr8vr=hjz)f-wet8fo$@+8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']  # Allow all hosts for development


# Application definition

INSTALLED_APPS = [
    "daphne",
    "channels",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "menu",
    "Analytics",
    "appointment",
    'voice',
    'whatsapp',
]
# EMAIL_BACKEND    = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST       = 'smtp.gmail.com'
# EMAIL_PORT       = 587
# EMAIL_USE_TLS    = True
# EMAIL_HOST_USER  = os.getenv('EMAIL_HOST_USER', 'alihassan9682@gmail.com')
# EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'fctj lcfy qnjz fuen')  # Gmail App Password

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kfc_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kfc_api.wsgi.application'
ASGI_APPLICATION = 'kfc_api.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Configuration for Eleven Labs webhooks
CORS_ALLOW_ALL_ORIGINS = True  # For development - allows all origins
CORS_ALLOW_CREDENTIALS = True

# CSRF Configuration for API
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:*',
    'http://127.0.0.1:*',
    'https://*.elevenlabs.io',
    'https://*.green-api.com',
    # Meta / WhatsApp Business Cloud API
    'https://*.facebook.com',
    'https://*.whatsapp.com',
    'https://*.fbcdn.net',
    # Dev tunnel (local testing with Meta)
    'https://*.devtunnels.ms',
    # Railway production
    'https://*.up.railway.app',
]

# Exempt API endpoints from CSRF for external webhooks
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'DEFAULT_PERMISSION_CLASSES': [],
}

# ElevenLabs Configuration
ELEVENLABS_API_KEY = os.getenv('ELEVENLABS_API_KEY')
ELEVENLABS_AGENT_ID = os.getenv('ELEVENLABS_AGENT_ID') or os.getenv('AGENT_ID')
ELEVENLABS_VOICE_ID = os.getenv('ELEVENLABS_VOICE_ID')
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')
GROQ_API_KEY = os.getenv('GROQ_API_KEY')
DEEPGRAM_API_KEY = os.getenv('DEEPGRAM_API_KEY')

# Green API (WhatsApp Bot)
GREENAPI_INSTANCE_ID = os.getenv('GREENAPI_INSTANCE_ID')
GREENAPI_API_TOKEN = os.getenv('GREENAPI_API_TOKEN')

