# Generated by Django 5.2.11 on 2026-03-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiSessionCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Unique session identifier for the voice call', max_length=255, unique=True)),
                ('agent_type', models.CharField(help_text='The type of agent, e.g., healthcare, restaurant', max_length=50)),
                ('prompt_tokens', models.IntegerField(default=0, help_text='Number of prompt tokens used')),
                ('response_tokens', models.IntegerField(default=0, help_text='Number of response tokens used')),
                ('total_tokens', models.IntegerField(default=0, help_text='Total tokens used in this session')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
