# Generated by Django 5.2.11 on 2026-03-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Unique session identifier matching GeminiSessionCost', max_length=255, unique=True)),
                ('agent_type', models.CharField(help_text='The type of agent, e.g., healthcare, restaurant', max_length=50)),
                ('duration_seconds', models.IntegerField(default=0, help_text='Duration of the WebSocket connection in seconds')),
                ('transcript', models.JSONField(default=list, help_text='List of JSON objects representing the conversation turns')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
