# Generated by Django 5.2.11 on 2026-03-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0002_callhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='geminisessioncost',
            name='estimated_cost_usd',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text='Estimated cost based on $3 per 1M input / $12 per 1M output audio tokens', max_digits=10),
        ),
    ]
