# Generated by Django 5.2.11 on 2026-03-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0003_geminisessioncost_estimated_cost_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='geminisessioncost',
            name='call_duration_seconds',
            field=models.IntegerField(default=0, help_text='Duration of the voice call in seconds'),
        ),
        migrations.AddField(
            model_name='geminisessioncost',
            name='input_audio_tokens',
            field=models.IntegerField(default=0, help_text='Number of input audio tokens (user speech)'),
        ),
        migrations.AddField(
            model_name='geminisessioncost',
            name='output_audio_tokens',
            field=models.IntegerField(default=0, help_text='Number of output audio tokens (agent speech)'),
        ),
    ]
