# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0004_geminisessioncost_call_duration_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geminisessioncost',
            name='input_text_tokens',
            field=models.IntegerField(default=0, help_text='Number of input text tokens (system prompt + conversation text)'),
        ),
        migrations.AddField(
            model_name='geminisessioncost',
            name='output_text_tokens',
            field=models.IntegerField(default=0, help_text='Number of output text tokens (model text/thinking)'),
        ),
    ]
